import { User, Tournament } from '../types';
import { DEFAULT_AVATAR } from './assets';

export const currentUser: User = {
  id: '1',
  uid: '1234567890',
  username: 'Subhan',
  fullName: 'Subhan Gamer',
  level: 25,
  walletBalance: 2450,
  rank: 'Diamond IV',
  rankPoints: 3420,
  totalMatches: 128,
  totalWins: 47,
  winRate: 36,
  totalKills: 450,
  totalEarnings: 4250,
  highestKills: 18,
  kdRatio: 3.25,
  avatarUrl: DEFAULT_AVATAR,
  joinedDate: '12/01/2024',
  inGameName: 'PK_Subhan_YT',
  gameUid: '5291048293'
};

export const tournaments: Tournament[] = [
  {
    id: 't1',
    title: 'ERANGEL SURVIVAL CUP',
    type: 'ERANGEL',
    mode: 'SOLO',
    time: '12:00 PM',
    status: 'LIVE',
    prizePool: 1500,
    entryFee: 50,
    spotsTotal: 50,
    spotsFilled: 48,
    map: 'Erangel',
    image: '/match-card.png',
  },
  {
    id: 't2',
    title: 'MIRAMar SNIPER BATTLE',
    type: 'MIRAMAR',
    mode: 'DUO',
    time: '01:00 PM',
    status: 'UPCOMING',
    prizePool: 1300,
    entryFee: 30,
    perKill: 30,
    spotsTotal: 50,
    spotsFilled: 36,
    map: 'Miramar',
    image: '/match-card.png',
  },
  {
    id: 't3',
    title: 'LIVIK FAST RUSH',
    type: 'LIVIK',
    mode: 'TRIO',
    time: '02:00 PM',
    status: 'UPCOMING',
    prizePool: 1800,
    entryFee: 60,
    spotsTotal: 45,
    spotsFilled: 24,
    map: 'Livik',
    image: '/match-card.png',
  },
  {
    id: 't4',
    title: 'TDM 4v4 CHAMPIONSHIP',
    type: 'TDM',
    mode: 'SQUAD',
    time: '03:00 PM',
    status: 'UPCOMING',
    prizePool: 2000,
    entryFee: 80,
    spotsTotal: 40,
    spotsFilled: 20,
    map: 'Warehouse',
    image: '/match-card.png',
  },
  {
    id: 't5',
    title: 'SANHOK BOOTCAMP CLASH',
    type: 'SANHOK',
    mode: 'SQUAD',
    time: '04:00 PM',
    status: 'UPCOMING',
    prizePool: 2500,
    entryFee: 100,
    spotsTotal: 60,
    spotsFilled: 32,
    map: 'Sanhok',
    image: '/match-card.png',
  },
  {
    id: 't6',
    title: 'ERANGEL SQUAD MASTERS',
    type: 'ERANGEL',
    mode: 'SQUAD',
    time: '05:00 PM',
    status: 'UPCOMING',
    prizePool: 3000,
    entryFee: 120,
    spotsTotal: 100,
    spotsFilled: 64,
    map: 'Erangel',
    image: '/match-card.png',
  },
  {
    id: 't7',
    title: 'SANHOK TRIO SURVIVORS',
    type: 'SANHOK',
    mode: 'TRIO',
    time: '06:00 PM',
    status: 'UPCOMING',
    prizePool: 2100,
    entryFee: 75,
    spotsTotal: 45,
    spotsFilled: 18,
    map: 'Sanhok',
    image: '/match-card.png',
  },
  {
    id: 't8',
    title: 'SUNDAY SPECIAL EVENT',
    type: 'EVENT',
    mode: 'DUO',
    time: '08:00 PM',
    status: 'UPCOMING',
    prizePool: 5000,
    entryFee: 100,
    spotsTotal: 100,
    spotsFilled: 0,
    map: 'Erangel',
    image: '/match-card.png',
  }
];
